### ISSUE TITLE
We should document roles

### ISSUE THREAD

**Issue by KipHamiltons** [NUbots/NUbook#110]
There are many roles. I don't know the purpose of most of them.

We should find out what each of them is for and write it down.

**Comment by ysims** [comment]
I'll try to have a look at doing this soon. 
Otherwise some ideas for whoever does:
Writing up what roles are useful when. Eg keyboardwalk for events, and for testing robot motions. Sensortest for testing odometry and testing if servos are broken (eg I was to see if there are shoulder issues without making the robot move). Cameratest for testing cameras and checking config (eg camera IDs) without visual mesh stuff. Scriptrunner pretty much all the time for standing.
