### ISSUE TITLE
Fix search in `yarn dev` and also when you click the NUbots logo in the top left of the page

### ISSUE THREAD

**Issue by ysims** [NUbots/NUbook#165]
When previewing the site in `yarn dev`, the search doesn't work.

**Comment by JosephusPaye** [comment]
The issue here is that in development [this](https://github.com/NUbots/NUbook/blob/36530b07d0fa9987773d6196627bc3a2bfd8681d/static/algolia-search.js#L19) is run before the search box is rendered, so Algolia doesn't find the element and throws an error.

The fix would be to wait until the `#search` element exists [using something like a MutationObserver](https://stackoverflow.com/a/16726669/5800506), and then instantiating Algolia.
